(cl:defpackage autofire-msg
  (:use )
  (:export
   "<SHOOTSWITCHACTION>"
   "SHOOTSWITCHACTION"
   "<SHOOTSWITCHACTIONFEEDBACK>"
   "SHOOTSWITCHACTIONFEEDBACK"
   "<SHOOTSWITCHACTIONGOAL>"
   "SHOOTSWITCHACTIONGOAL"
   "<SHOOTSWITCHACTIONRESULT>"
   "SHOOTSWITCHACTIONRESULT"
   "<SHOOTSWITCHFEEDBACK>"
   "SHOOTSWITCHFEEDBACK"
   "<SHOOTSWITCHGOAL>"
   "SHOOTSWITCHGOAL"
   "<SHOOTSWITCHRESULT>"
   "SHOOTSWITCHRESULT"
   "<ENEMY_ID>"
   "ENEMY_ID"
  ))

