; Auto-generated. Do not edit!


(cl:in-package autofire-msg)


;//! \htmlinclude ShootSwitchResult.msg.html

(cl:defclass <ShootSwitchResult> (roslisp-msg-protocol:ros-message)
  ((is_finished
    :reader is_finished
    :initarg :is_finished
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ShootSwitchResult (<ShootSwitchResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ShootSwitchResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ShootSwitchResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autofire-msg:<ShootSwitchResult> is deprecated: use autofire-msg:ShootSwitchResult instead.")))

(cl:ensure-generic-function 'is_finished-val :lambda-list '(m))
(cl:defmethod is_finished-val ((m <ShootSwitchResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autofire-msg:is_finished-val is deprecated.  Use autofire-msg:is_finished instead.")
  (is_finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ShootSwitchResult>) ostream)
  "Serializes a message object of type '<ShootSwitchResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_finished) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ShootSwitchResult>) istream)
  "Deserializes a message object of type '<ShootSwitchResult>"
    (cl:setf (cl:slot-value msg 'is_finished) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ShootSwitchResult>)))
  "Returns string type for a message object of type '<ShootSwitchResult>"
  "autofire/ShootSwitchResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ShootSwitchResult)))
  "Returns string type for a message object of type 'ShootSwitchResult"
  "autofire/ShootSwitchResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ShootSwitchResult>)))
  "Returns md5sum for a message object of type '<ShootSwitchResult>"
  "039e37637b9ee4ca0ff88874a3971b20")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ShootSwitchResult)))
  "Returns md5sum for a message object of type 'ShootSwitchResult"
  "039e37637b9ee4ca0ff88874a3971b20")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ShootSwitchResult>)))
  "Returns full string definition for message of type '<ShootSwitchResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finished #0 dead 1 no enemy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ShootSwitchResult)))
  "Returns full string definition for message of type 'ShootSwitchResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finished #0 dead 1 no enemy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ShootSwitchResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ShootSwitchResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ShootSwitchResult
    (cl:cons ':is_finished (is_finished msg))
))
