; Auto-generated. Do not edit!


(cl:in-package autofire-msg)


;//! \htmlinclude ShootSwitchGoal.msg.html

(cl:defclass <ShootSwitchGoal> (roslisp-msg-protocol:ros-message)
  ((cmd_id
    :reader cmd_id
    :initarg :cmd_id
    :type cl:integer
    :initform 0))
)

(cl:defclass ShootSwitchGoal (<ShootSwitchGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ShootSwitchGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ShootSwitchGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autofire-msg:<ShootSwitchGoal> is deprecated: use autofire-msg:ShootSwitchGoal instead.")))

(cl:ensure-generic-function 'cmd_id-val :lambda-list '(m))
(cl:defmethod cmd_id-val ((m <ShootSwitchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autofire-msg:cmd_id-val is deprecated.  Use autofire-msg:cmd_id instead.")
  (cmd_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ShootSwitchGoal>) ostream)
  "Serializes a message object of type '<ShootSwitchGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'cmd_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'cmd_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'cmd_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'cmd_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ShootSwitchGoal>) istream)
  "Deserializes a message object of type '<ShootSwitchGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'cmd_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'cmd_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'cmd_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'cmd_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ShootSwitchGoal>)))
  "Returns string type for a message object of type '<ShootSwitchGoal>"
  "autofire/ShootSwitchGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ShootSwitchGoal)))
  "Returns string type for a message object of type 'ShootSwitchGoal"
  "autofire/ShootSwitchGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ShootSwitchGoal>)))
  "Returns md5sum for a message object of type '<ShootSwitchGoal>"
  "2a153ff01b10e544dddcef41f8843134")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ShootSwitchGoal)))
  "Returns md5sum for a message object of type 'ShootSwitchGoal"
  "2a153ff01b10e544dddcef41f8843134")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ShootSwitchGoal>)))
  "Returns full string definition for message of type '<ShootSwitchGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 cmd_id  # Specify which robot we want to recharge 1 enable 2 disable ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ShootSwitchGoal)))
  "Returns full string definition for message of type 'ShootSwitchGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 cmd_id  # Specify which robot we want to recharge 1 enable 2 disable ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ShootSwitchGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ShootSwitchGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ShootSwitchGoal
    (cl:cons ':cmd_id (cmd_id msg))
))
