; Auto-generated. Do not edit!


(cl:in-package modified_chassis-msg)


;//! \htmlinclude MoveModeFeedback.msg.html

(cl:defclass <MoveModeFeedback> (roslisp-msg-protocol:ros-message)
  ((state_keeping
    :reader state_keeping
    :initarg :state_keeping
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveModeFeedback (<MoveModeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveModeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveModeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name modified_chassis-msg:<MoveModeFeedback> is deprecated: use modified_chassis-msg:MoveModeFeedback instead.")))

(cl:ensure-generic-function 'state_keeping-val :lambda-list '(m))
(cl:defmethod state_keeping-val ((m <MoveModeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader modified_chassis-msg:state_keeping-val is deprecated.  Use modified_chassis-msg:state_keeping instead.")
  (state_keeping m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveModeFeedback>) ostream)
  "Serializes a message object of type '<MoveModeFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'state_keeping))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveModeFeedback>) istream)
  "Deserializes a message object of type '<MoveModeFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'state_keeping) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveModeFeedback>)))
  "Returns string type for a message object of type '<MoveModeFeedback>"
  "modified_chassis/MoveModeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveModeFeedback)))
  "Returns string type for a message object of type 'MoveModeFeedback"
  "modified_chassis/MoveModeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveModeFeedback>)))
  "Returns md5sum for a message object of type '<MoveModeFeedback>"
  "f643aa8d8b0e9b88fb16c443fac7ea19")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveModeFeedback)))
  "Returns md5sum for a message object of type 'MoveModeFeedback"
  "f643aa8d8b0e9b88fb16c443fac7ea19")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveModeFeedback>)))
  "Returns full string definition for message of type '<MoveModeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 state_keeping~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveModeFeedback)))
  "Returns full string definition for message of type 'MoveModeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 state_keeping~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveModeFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveModeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveModeFeedback
    (cl:cons ':state_keeping (state_keeping msg))
))
