; Auto-generated. Do not edit!


(cl:in-package modified_chassis-msg)


;//! \htmlinclude MoveModeGoal.msg.html

(cl:defclass <MoveModeGoal> (roslisp-msg-protocol:ros-message)
  ((mode
    :reader mode
    :initarg :mode
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MoveModeGoal (<MoveModeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveModeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveModeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name modified_chassis-msg:<MoveModeGoal> is deprecated: use modified_chassis-msg:MoveModeGoal instead.")))

(cl:ensure-generic-function 'mode-val :lambda-list '(m))
(cl:defmethod mode-val ((m <MoveModeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader modified_chassis-msg:mode-val is deprecated.  Use modified_chassis-msg:mode instead.")
  (mode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveModeGoal>) ostream)
  "Serializes a message object of type '<MoveModeGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'mode) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveModeGoal>) istream)
  "Deserializes a message object of type '<MoveModeGoal>"
    (cl:setf (cl:slot-value msg 'mode) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveModeGoal>)))
  "Returns string type for a message object of type '<MoveModeGoal>"
  "modified_chassis/MoveModeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveModeGoal)))
  "Returns string type for a message object of type 'MoveModeGoal"
  "modified_chassis/MoveModeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveModeGoal>)))
  "Returns md5sum for a message object of type '<MoveModeGoal>"
  "f3124ebba8ebedcd8ba82847d482ceb7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveModeGoal)))
  "Returns md5sum for a message object of type 'MoveModeGoal"
  "f3124ebba8ebedcd8ba82847d482ceb7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveModeGoal>)))
  "Returns full string definition for message of type '<MoveModeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%bool mode  # Specify which robot we want to recharge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveModeGoal)))
  "Returns full string definition for message of type 'MoveModeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%bool mode  # Specify which robot we want to recharge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveModeGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveModeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveModeGoal
    (cl:cons ':mode (mode msg))
))
