; Auto-generated. Do not edit!


(cl:in-package modified_chassis-msg)


;//! \htmlinclude RechargeGoal.msg.html

(cl:defclass <RechargeGoal> (roslisp-msg-protocol:ros-message)
  ((robot_id
    :reader robot_id
    :initarg :robot_id
    :type cl:integer
    :initform 0))
)

(cl:defclass RechargeGoal (<RechargeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RechargeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RechargeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name modified_chassis-msg:<RechargeGoal> is deprecated: use modified_chassis-msg:RechargeGoal instead.")))

(cl:ensure-generic-function 'robot_id-val :lambda-list '(m))
(cl:defmethod robot_id-val ((m <RechargeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader modified_chassis-msg:robot_id-val is deprecated.  Use modified_chassis-msg:robot_id instead.")
  (robot_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RechargeGoal>) ostream)
  "Serializes a message object of type '<RechargeGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'robot_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RechargeGoal>) istream)
  "Deserializes a message object of type '<RechargeGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RechargeGoal>)))
  "Returns string type for a message object of type '<RechargeGoal>"
  "modified_chassis/RechargeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RechargeGoal)))
  "Returns string type for a message object of type 'RechargeGoal"
  "modified_chassis/RechargeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RechargeGoal>)))
  "Returns md5sum for a message object of type '<RechargeGoal>"
  "643c2c9b3dd26758833f013bbe8b0a36")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RechargeGoal)))
  "Returns md5sum for a message object of type 'RechargeGoal"
  "643c2c9b3dd26758833f013bbe8b0a36")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RechargeGoal>)))
  "Returns full string definition for message of type '<RechargeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 robot_id  # Specify which robot we want to recharge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RechargeGoal)))
  "Returns full string definition for message of type 'RechargeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 robot_id  # Specify which robot we want to recharge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RechargeGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RechargeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RechargeGoal
    (cl:cons ':robot_id (robot_id msg))
))
