; Auto-generated. Do not edit!


(cl:in-package modified_chassis-msg)


;//! \htmlinclude RechargeResult.msg.html

(cl:defclass <RechargeResult> (roslisp-msg-protocol:ros-message)
  ((is_finished
    :reader is_finished
    :initarg :is_finished
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass RechargeResult (<RechargeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RechargeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RechargeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name modified_chassis-msg:<RechargeResult> is deprecated: use modified_chassis-msg:RechargeResult instead.")))

(cl:ensure-generic-function 'is_finished-val :lambda-list '(m))
(cl:defmethod is_finished-val ((m <RechargeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader modified_chassis-msg:is_finished-val is deprecated.  Use modified_chassis-msg:is_finished instead.")
  (is_finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RechargeResult>) ostream)
  "Serializes a message object of type '<RechargeResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_finished) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RechargeResult>) istream)
  "Deserializes a message object of type '<RechargeResult>"
    (cl:setf (cl:slot-value msg 'is_finished) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RechargeResult>)))
  "Returns string type for a message object of type '<RechargeResult>"
  "modified_chassis/RechargeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RechargeResult)))
  "Returns string type for a message object of type 'RechargeResult"
  "modified_chassis/RechargeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RechargeResult>)))
  "Returns md5sum for a message object of type '<RechargeResult>"
  "039e37637b9ee4ca0ff88874a3971b20")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RechargeResult)))
  "Returns md5sum for a message object of type 'RechargeResult"
  "039e37637b9ee4ca0ff88874a3971b20")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RechargeResult>)))
  "Returns full string definition for message of type '<RechargeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RechargeResult)))
  "Returns full string definition for message of type 'RechargeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RechargeResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RechargeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RechargeResult
    (cl:cons ':is_finished (is_finished msg))
))
