// Generated by gencpp from file modified_chassis/MoveModeResponse.msg
// DO NOT EDIT!


#ifndef MODIFIED_CHASSIS_MESSAGE_MOVEMODERESPONSE_H
#define MODIFIED_CHASSIS_MESSAGE_MOVEMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modified_chassis
{
template <class ContainerAllocator>
struct MoveModeResponse_
{
  typedef MoveModeResponse_<ContainerAllocator> Type;

  MoveModeResponse_()
    : received(false)  {
    }
  MoveModeResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::modified_chassis::MoveModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modified_chassis::MoveModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveModeResponse_

typedef ::modified_chassis::MoveModeResponse_<std::allocator<void> > MoveModeResponse;

typedef boost::shared_ptr< ::modified_chassis::MoveModeResponse > MoveModeResponsePtr;
typedef boost::shared_ptr< ::modified_chassis::MoveModeResponse const> MoveModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modified_chassis::MoveModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modified_chassis::MoveModeResponse_<ContainerAllocator1> & lhs, const ::modified_chassis::MoveModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modified_chassis::MoveModeResponse_<ContainerAllocator1> & lhs, const ::modified_chassis::MoveModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modified_chassis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::MoveModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::MoveModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::MoveModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::modified_chassis::MoveModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modified_chassis/MoveModeResponse";
  }

  static const char* value(const ::modified_chassis::MoveModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"\n"
;
  }

  static const char* value(const ::modified_chassis::MoveModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modified_chassis::MoveModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modified_chassis::MoveModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODIFIED_CHASSIS_MESSAGE_MOVEMODERESPONSE_H
