// Generated by gencpp from file modified_chassis/MoveMode.msg
// DO NOT EDIT!


#ifndef MODIFIED_CHASSIS_MESSAGE_MOVEMODE_H
#define MODIFIED_CHASSIS_MESSAGE_MOVEMODE_H

#include <ros/service_traits.h>


#include <modified_chassis/MoveModeRequest.h>
#include <modified_chassis/MoveModeResponse.h>


namespace modified_chassis
{

struct MoveMode
{

typedef MoveModeRequest Request;
typedef MoveModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveMode
} // namespace modified_chassis


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::modified_chassis::MoveMode > {
  static const char* value()
  {
    return "e5d38bc3f9d0bc1f71af55e7a5ccf455";
  }

  static const char* value(const ::modified_chassis::MoveMode&) { return value(); }
};

template<>
struct DataType< ::modified_chassis::MoveMode > {
  static const char* value()
  {
    return "modified_chassis/MoveMode";
  }

  static const char* value(const ::modified_chassis::MoveMode&) { return value(); }
};


// service_traits::MD5Sum< ::modified_chassis::MoveModeRequest> should match
// service_traits::MD5Sum< ::modified_chassis::MoveMode >
template<>
struct MD5Sum< ::modified_chassis::MoveModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::modified_chassis::MoveMode >::value();
  }
  static const char* value(const ::modified_chassis::MoveModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::modified_chassis::MoveModeRequest> should match
// service_traits::DataType< ::modified_chassis::MoveMode >
template<>
struct DataType< ::modified_chassis::MoveModeRequest>
{
  static const char* value()
  {
    return DataType< ::modified_chassis::MoveMode >::value();
  }
  static const char* value(const ::modified_chassis::MoveModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::modified_chassis::MoveModeResponse> should match
// service_traits::MD5Sum< ::modified_chassis::MoveMode >
template<>
struct MD5Sum< ::modified_chassis::MoveModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::modified_chassis::MoveMode >::value();
  }
  static const char* value(const ::modified_chassis::MoveModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::modified_chassis::MoveModeResponse> should match
// service_traits::DataType< ::modified_chassis::MoveMode >
template<>
struct DataType< ::modified_chassis::MoveModeResponse>
{
  static const char* value()
  {
    return DataType< ::modified_chassis::MoveMode >::value();
  }
  static const char* value(const ::modified_chassis::MoveModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODIFIED_CHASSIS_MESSAGE_MOVEMODE_H
