// Generated by gencpp from file modified_chassis/MoveModeFeedback.msg
// DO NOT EDIT!


#ifndef MODIFIED_CHASSIS_MESSAGE_MOVEMODEFEEDBACK_H
#define MODIFIED_CHASSIS_MESSAGE_MOVEMODEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modified_chassis
{
template <class ContainerAllocator>
struct MoveModeFeedback_
{
  typedef MoveModeFeedback_<ContainerAllocator> Type;

  MoveModeFeedback_()
    : state_keeping(0.0)  {
    }
  MoveModeFeedback_(const ContainerAllocator& _alloc)
    : state_keeping(0.0)  {
  (void)_alloc;
    }



   typedef float _state_keeping_type;
  _state_keeping_type state_keeping;





  typedef boost::shared_ptr< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveModeFeedback_

typedef ::modified_chassis::MoveModeFeedback_<std::allocator<void> > MoveModeFeedback;

typedef boost::shared_ptr< ::modified_chassis::MoveModeFeedback > MoveModeFeedbackPtr;
typedef boost::shared_ptr< ::modified_chassis::MoveModeFeedback const> MoveModeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modified_chassis::MoveModeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modified_chassis::MoveModeFeedback_<ContainerAllocator1> & lhs, const ::modified_chassis::MoveModeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.state_keeping == rhs.state_keeping;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modified_chassis::MoveModeFeedback_<ContainerAllocator1> & lhs, const ::modified_chassis::MoveModeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modified_chassis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f643aa8d8b0e9b88fb16c443fac7ea19";
  }

  static const char* value(const ::modified_chassis::MoveModeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf643aa8d8b0e9b88ULL;
  static const uint64_t static_value2 = 0xfb16c443fac7ea19ULL;
};

template<class ContainerAllocator>
struct DataType< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modified_chassis/MoveModeFeedback";
  }

  static const char* value(const ::modified_chassis::MoveModeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 state_keeping\n"
"\n"
;
  }

  static const char* value(const ::modified_chassis::MoveModeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_keeping);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveModeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modified_chassis::MoveModeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modified_chassis::MoveModeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state_keeping: ";
    Printer<float>::stream(s, indent + "  ", v.state_keeping);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODIFIED_CHASSIS_MESSAGE_MOVEMODEFEEDBACK_H
