// Generated by gencpp from file modified_chassis/RechargeFeedback.msg
// DO NOT EDIT!


#ifndef MODIFIED_CHASSIS_MESSAGE_RECHARGEFEEDBACK_H
#define MODIFIED_CHASSIS_MESSAGE_RECHARGEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modified_chassis
{
template <class ContainerAllocator>
struct RechargeFeedback_
{
  typedef RechargeFeedback_<ContainerAllocator> Type;

  RechargeFeedback_()
    : percent_complete(0.0)  {
    }
  RechargeFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::modified_chassis::RechargeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modified_chassis::RechargeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RechargeFeedback_

typedef ::modified_chassis::RechargeFeedback_<std::allocator<void> > RechargeFeedback;

typedef boost::shared_ptr< ::modified_chassis::RechargeFeedback > RechargeFeedbackPtr;
typedef boost::shared_ptr< ::modified_chassis::RechargeFeedback const> RechargeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modified_chassis::RechargeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modified_chassis::RechargeFeedback_<ContainerAllocator1> & lhs, const ::modified_chassis::RechargeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modified_chassis::RechargeFeedback_<ContainerAllocator1> & lhs, const ::modified_chassis::RechargeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modified_chassis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modified_chassis::RechargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modified_chassis::RechargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modified_chassis::RechargeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::modified_chassis::RechargeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modified_chassis/RechargeFeedback";
  }

  static const char* value(const ::modified_chassis::RechargeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
"\n"
;
  }

  static const char* value(const ::modified_chassis::RechargeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RechargeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modified_chassis::RechargeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modified_chassis::RechargeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODIFIED_CHASSIS_MESSAGE_RECHARGEFEEDBACK_H
