// Generated by gencpp from file autofire/enemy_id.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_ENEMY_ID_H
#define AUTOFIRE_MESSAGE_ENEMY_ID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct enemy_id_
{
  typedef enemy_id_<ContainerAllocator> Type;

  enemy_id_()
    : x(0.0)
    , y(0.0)
    , id()  {
    }
  enemy_id_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::autofire::enemy_id_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::enemy_id_<ContainerAllocator> const> ConstPtr;

}; // struct enemy_id_

typedef ::autofire::enemy_id_<std::allocator<void> > enemy_id;

typedef boost::shared_ptr< ::autofire::enemy_id > enemy_idPtr;
typedef boost::shared_ptr< ::autofire::enemy_id const> enemy_idConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::enemy_id_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::enemy_id_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::enemy_id_<ContainerAllocator1> & lhs, const ::autofire::enemy_id_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::enemy_id_<ContainerAllocator1> & lhs, const ::autofire::enemy_id_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::enemy_id_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::enemy_id_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::enemy_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::enemy_id_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::enemy_id_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::enemy_id_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::enemy_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7993d0d3043d5146dda81224aff3279c";
  }

  static const char* value(const ::autofire::enemy_id_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7993d0d3043d5146ULL;
  static const uint64_t static_value2 = 0xdda81224aff3279cULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::enemy_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/enemy_id";
  }

  static const char* value(const ::autofire::enemy_id_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::enemy_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"string id\n"
;
  }

  static const char* value(const ::autofire::enemy_id_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::enemy_id_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enemy_id_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::enemy_id_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::enemy_id_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_ENEMY_ID_H
