// Generated by gencpp from file autofire/Lidar2EnemyResponse.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_LIDAR2ENEMYRESPONSE_H
#define AUTOFIRE_MESSAGE_LIDAR2ENEMYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct Lidar2EnemyResponse_
{
  typedef Lidar2EnemyResponse_<ContainerAllocator> Type;

  Lidar2EnemyResponse_()
    : received(false)  {
    }
  Lidar2EnemyResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Lidar2EnemyResponse_

typedef ::autofire::Lidar2EnemyResponse_<std::allocator<void> > Lidar2EnemyResponse;

typedef boost::shared_ptr< ::autofire::Lidar2EnemyResponse > Lidar2EnemyResponsePtr;
typedef boost::shared_ptr< ::autofire::Lidar2EnemyResponse const> Lidar2EnemyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::Lidar2EnemyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::Lidar2EnemyResponse_<ContainerAllocator1> & lhs, const ::autofire::Lidar2EnemyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::Lidar2EnemyResponse_<ContainerAllocator1> & lhs, const ::autofire::Lidar2EnemyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::autofire::Lidar2EnemyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/Lidar2EnemyResponse";
  }

  static const char* value(const ::autofire::Lidar2EnemyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"\n"
;
  }

  static const char* value(const ::autofire::Lidar2EnemyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lidar2EnemyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::Lidar2EnemyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::Lidar2EnemyResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_LIDAR2ENEMYRESPONSE_H
