// Generated by gencpp from file autofire/Lidar2Enemy.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_LIDAR2ENEMY_H
#define AUTOFIRE_MESSAGE_LIDAR2ENEMY_H

#include <ros/service_traits.h>


#include <autofire/Lidar2EnemyRequest.h>
#include <autofire/Lidar2EnemyResponse.h>


namespace autofire
{

struct Lidar2Enemy
{

typedef Lidar2EnemyRequest Request;
typedef Lidar2EnemyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Lidar2Enemy
} // namespace autofire


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autofire::Lidar2Enemy > {
  static const char* value()
  {
    return "5c20fa677eb90ce8ed6acc054aa17bb1";
  }

  static const char* value(const ::autofire::Lidar2Enemy&) { return value(); }
};

template<>
struct DataType< ::autofire::Lidar2Enemy > {
  static const char* value()
  {
    return "autofire/Lidar2Enemy";
  }

  static const char* value(const ::autofire::Lidar2Enemy&) { return value(); }
};


// service_traits::MD5Sum< ::autofire::Lidar2EnemyRequest> should match
// service_traits::MD5Sum< ::autofire::Lidar2Enemy >
template<>
struct MD5Sum< ::autofire::Lidar2EnemyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autofire::Lidar2Enemy >::value();
  }
  static const char* value(const ::autofire::Lidar2EnemyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autofire::Lidar2EnemyRequest> should match
// service_traits::DataType< ::autofire::Lidar2Enemy >
template<>
struct DataType< ::autofire::Lidar2EnemyRequest>
{
  static const char* value()
  {
    return DataType< ::autofire::Lidar2Enemy >::value();
  }
  static const char* value(const ::autofire::Lidar2EnemyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autofire::Lidar2EnemyResponse> should match
// service_traits::MD5Sum< ::autofire::Lidar2Enemy >
template<>
struct MD5Sum< ::autofire::Lidar2EnemyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autofire::Lidar2Enemy >::value();
  }
  static const char* value(const ::autofire::Lidar2EnemyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autofire::Lidar2EnemyResponse> should match
// service_traits::DataType< ::autofire::Lidar2Enemy >
template<>
struct DataType< ::autofire::Lidar2EnemyResponse>
{
  static const char* value()
  {
    return DataType< ::autofire::Lidar2Enemy >::value();
  }
  static const char* value(const ::autofire::Lidar2EnemyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOFIRE_MESSAGE_LIDAR2ENEMY_H
