// Generated by gencpp from file autofire/Lidar2EnemyRequest.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_LIDAR2ENEMYREQUEST_H
#define AUTOFIRE_MESSAGE_LIDAR2ENEMYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct Lidar2EnemyRequest_
{
  typedef Lidar2EnemyRequest_<ContainerAllocator> Type;

  Lidar2EnemyRequest_()
    : setStatus(false)  {
    }
  Lidar2EnemyRequest_(const ContainerAllocator& _alloc)
    : setStatus(false)  {
  (void)_alloc;
    }



   typedef uint8_t _setStatus_type;
  _setStatus_type setStatus;





  typedef boost::shared_ptr< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Lidar2EnemyRequest_

typedef ::autofire::Lidar2EnemyRequest_<std::allocator<void> > Lidar2EnemyRequest;

typedef boost::shared_ptr< ::autofire::Lidar2EnemyRequest > Lidar2EnemyRequestPtr;
typedef boost::shared_ptr< ::autofire::Lidar2EnemyRequest const> Lidar2EnemyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::Lidar2EnemyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::Lidar2EnemyRequest_<ContainerAllocator1> & lhs, const ::autofire::Lidar2EnemyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.setStatus == rhs.setStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::Lidar2EnemyRequest_<ContainerAllocator1> & lhs, const ::autofire::Lidar2EnemyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba94cb4a8b514e916b961ea5660ffd7";
  }

  static const char* value(const ::autofire::Lidar2EnemyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba94cb4a8b514e9ULL;
  static const uint64_t static_value2 = 0x16b961ea5660ffd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/Lidar2EnemyRequest";
  }

  static const char* value(const ::autofire::Lidar2EnemyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool setStatus\n"
;
  }

  static const char* value(const ::autofire::Lidar2EnemyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lidar2EnemyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::Lidar2EnemyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::Lidar2EnemyRequest_<ContainerAllocator>& v)
  {
    s << indent << "setStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_LIDAR2ENEMYREQUEST_H
