// Generated by gencpp from file autofire/ShootSwitchFeedback.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_SHOOTSWITCHFEEDBACK_H
#define AUTOFIRE_MESSAGE_SHOOTSWITCHFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct ShootSwitchFeedback_
{
  typedef ShootSwitchFeedback_<ContainerAllocator> Type;

  ShootSwitchFeedback_()
    : percent_complete(0.0)  {
    }
  ShootSwitchFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::autofire::ShootSwitchFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::ShootSwitchFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ShootSwitchFeedback_

typedef ::autofire::ShootSwitchFeedback_<std::allocator<void> > ShootSwitchFeedback;

typedef boost::shared_ptr< ::autofire::ShootSwitchFeedback > ShootSwitchFeedbackPtr;
typedef boost::shared_ptr< ::autofire::ShootSwitchFeedback const> ShootSwitchFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::ShootSwitchFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::ShootSwitchFeedback_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::ShootSwitchFeedback_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::autofire::ShootSwitchFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/ShootSwitchFeedback";
  }

  static const char* value(const ::autofire::ShootSwitchFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
"\n"
;
  }

  static const char* value(const ::autofire::ShootSwitchFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootSwitchFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::ShootSwitchFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::ShootSwitchFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_SHOOTSWITCHFEEDBACK_H
