// Generated by gencpp from file autofire/ShootSwitchResponse.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_SHOOTSWITCHRESPONSE_H
#define AUTOFIRE_MESSAGE_SHOOTSWITCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct ShootSwitchResponse_
{
  typedef ShootSwitchResponse_<ContainerAllocator> Type;

  ShootSwitchResponse_()
    : status(false)  {
    }
  ShootSwitchResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::autofire::ShootSwitchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::ShootSwitchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ShootSwitchResponse_

typedef ::autofire::ShootSwitchResponse_<std::allocator<void> > ShootSwitchResponse;

typedef boost::shared_ptr< ::autofire::ShootSwitchResponse > ShootSwitchResponsePtr;
typedef boost::shared_ptr< ::autofire::ShootSwitchResponse const> ShootSwitchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::ShootSwitchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::ShootSwitchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::ShootSwitchResponse_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::ShootSwitchResponse_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::autofire::ShootSwitchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/ShootSwitchResponse";
  }

  static const char* value(const ::autofire::ShootSwitchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::autofire::ShootSwitchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootSwitchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::ShootSwitchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::ShootSwitchResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_SHOOTSWITCHRESPONSE_H
