// Generated by gencpp from file autofire/ShootSwitchResult.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_SHOOTSWITCHRESULT_H
#define AUTOFIRE_MESSAGE_SHOOTSWITCHRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct ShootSwitchResult_
{
  typedef ShootSwitchResult_<ContainerAllocator> Type;

  ShootSwitchResult_()
    : is_finished(false)  {
    }
  ShootSwitchResult_(const ContainerAllocator& _alloc)
    : is_finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_finished_type;
  _is_finished_type is_finished;





  typedef boost::shared_ptr< ::autofire::ShootSwitchResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::ShootSwitchResult_<ContainerAllocator> const> ConstPtr;

}; // struct ShootSwitchResult_

typedef ::autofire::ShootSwitchResult_<std::allocator<void> > ShootSwitchResult;

typedef boost::shared_ptr< ::autofire::ShootSwitchResult > ShootSwitchResultPtr;
typedef boost::shared_ptr< ::autofire::ShootSwitchResult const> ShootSwitchResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::ShootSwitchResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::ShootSwitchResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::ShootSwitchResult_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchResult_<ContainerAllocator2> & rhs)
{
  return lhs.is_finished == rhs.is_finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::ShootSwitchResult_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::ShootSwitchResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "039e37637b9ee4ca0ff88874a3971b20";
  }

  static const char* value(const ::autofire::ShootSwitchResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x039e37637b9ee4caULL;
  static const uint64_t static_value2 = 0x0ff88874a3971b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::ShootSwitchResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/ShootSwitchResult";
  }

  static const char* value(const ::autofire::ShootSwitchResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::ShootSwitchResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"bool is_finished #0 dead 1 no enemy\n"
;
  }

  static const char* value(const ::autofire::ShootSwitchResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::ShootSwitchResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootSwitchResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::ShootSwitchResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::ShootSwitchResult_<ContainerAllocator>& v)
  {
    s << indent << "is_finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_SHOOTSWITCHRESULT_H
