// Generated by gencpp from file autofire/ShootSwitchRequest.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_SHOOTSWITCHREQUEST_H
#define AUTOFIRE_MESSAGE_SHOOTSWITCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autofire
{
template <class ContainerAllocator>
struct ShootSwitchRequest_
{
  typedef ShootSwitchRequest_<ContainerAllocator> Type;

  ShootSwitchRequest_()
    : enableShoot(false)  {
    }
  ShootSwitchRequest_(const ContainerAllocator& _alloc)
    : enableShoot(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enableShoot_type;
  _enableShoot_type enableShoot;





  typedef boost::shared_ptr< ::autofire::ShootSwitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autofire::ShootSwitchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShootSwitchRequest_

typedef ::autofire::ShootSwitchRequest_<std::allocator<void> > ShootSwitchRequest;

typedef boost::shared_ptr< ::autofire::ShootSwitchRequest > ShootSwitchRequestPtr;
typedef boost::shared_ptr< ::autofire::ShootSwitchRequest const> ShootSwitchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autofire::ShootSwitchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autofire::ShootSwitchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autofire::ShootSwitchRequest_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enableShoot == rhs.enableShoot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autofire::ShootSwitchRequest_<ContainerAllocator1> & lhs, const ::autofire::ShootSwitchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autofire

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autofire::ShootSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autofire::ShootSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autofire::ShootSwitchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "375fc33df4063c841279eb3b6c0bb3e9";
  }

  static const char* value(const ::autofire::ShootSwitchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x375fc33df4063c84ULL;
  static const uint64_t static_value2 = 0x1279eb3b6c0bb3e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autofire/ShootSwitchRequest";
  }

  static const char* value(const ::autofire::ShootSwitchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enableShoot\n"
;
  }

  static const char* value(const ::autofire::ShootSwitchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enableShoot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootSwitchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autofire::ShootSwitchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autofire::ShootSwitchRequest_<ContainerAllocator>& v)
  {
    s << indent << "enableShoot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableShoot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOFIRE_MESSAGE_SHOOTSWITCHREQUEST_H
