// Generated by gencpp from file autofire/ShootSwitch.msg
// DO NOT EDIT!


#ifndef AUTOFIRE_MESSAGE_SHOOTSWITCH_H
#define AUTOFIRE_MESSAGE_SHOOTSWITCH_H

#include <ros/service_traits.h>


#include <autofire/ShootSwitchRequest.h>
#include <autofire/ShootSwitchResponse.h>


namespace autofire
{

struct ShootSwitch
{

typedef ShootSwitchRequest Request;
typedef ShootSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShootSwitch
} // namespace autofire


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autofire::ShootSwitch > {
  static const char* value()
  {
    return "5d377b7485c09603dc7fd050a7504601";
  }

  static const char* value(const ::autofire::ShootSwitch&) { return value(); }
};

template<>
struct DataType< ::autofire::ShootSwitch > {
  static const char* value()
  {
    return "autofire/ShootSwitch";
  }

  static const char* value(const ::autofire::ShootSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::autofire::ShootSwitchRequest> should match
// service_traits::MD5Sum< ::autofire::ShootSwitch >
template<>
struct MD5Sum< ::autofire::ShootSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autofire::ShootSwitch >::value();
  }
  static const char* value(const ::autofire::ShootSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autofire::ShootSwitchRequest> should match
// service_traits::DataType< ::autofire::ShootSwitch >
template<>
struct DataType< ::autofire::ShootSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::autofire::ShootSwitch >::value();
  }
  static const char* value(const ::autofire::ShootSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autofire::ShootSwitchResponse> should match
// service_traits::MD5Sum< ::autofire::ShootSwitch >
template<>
struct MD5Sum< ::autofire::ShootSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autofire::ShootSwitch >::value();
  }
  static const char* value(const ::autofire::ShootSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autofire::ShootSwitchResponse> should match
// service_traits::DataType< ::autofire::ShootSwitch >
template<>
struct DataType< ::autofire::ShootSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::autofire::ShootSwitch >::value();
  }
  static const char* value(const ::autofire::ShootSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOFIRE_MESSAGE_SHOOTSWITCH_H
