// Auto-generated. Do not edit!

// (in-package autofire.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ShootSwitchResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.is_finished = null;
    }
    else {
      if (initObj.hasOwnProperty('is_finished')) {
        this.is_finished = initObj.is_finished
      }
      else {
        this.is_finished = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ShootSwitchResult
    // Serialize message field [is_finished]
    bufferOffset = _serializer.bool(obj.is_finished, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ShootSwitchResult
    let len;
    let data = new ShootSwitchResult(null);
    // Deserialize message field [is_finished]
    data.is_finished = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'autofire/ShootSwitchResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '039e37637b9ee4ca0ff88874a3971b20';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    bool is_finished #0 dead 1 no enemy
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ShootSwitchResult(null);
    if (msg.is_finished !== undefined) {
      resolved.is_finished = msg.is_finished;
    }
    else {
      resolved.is_finished = false
    }

    return resolved;
    }
};

module.exports = ShootSwitchResult;
