(cl:defpackage autofire-srv
  (:use )
  (:export
   "LIDAR2ENEMY"
   "<LIDAR2ENEMY-REQUEST>"
   "LIDAR2ENEMY-REQUEST"
   "<LIDAR2ENEMY-RESPONSE>"
   "LIDAR2ENEMY-RESPONSE"
   "SHOOTSWITCH"
   "<SHOOTSWITCH-REQUEST>"
   "SHOOTSWITCH-REQUEST"
   "<SHOOTSWITCH-RESPONSE>"
   "SHOOTSWITCH-RESPONSE"
  ))

