// Generated by gencpp from file ros_yolo/ArmorPoints.msg
// DO NOT EDIT!


#ifndef ROS_YOLO_MESSAGE_ARMORPOINTS_H
#define ROS_YOLO_MESSAGE_ARMORPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_yolo/Box.h>

namespace ros_yolo
{
template <class ContainerAllocator>
struct ArmorPoints_
{
  typedef ArmorPoints_<ContainerAllocator> Type;

  ArmorPoints_()
    : header()
    , numDetected(0)
    , bbox()  {
    }
  ArmorPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , numDetected(0)
    , bbox()  {
  (void)_alloc;
      bbox.assign( ::ros_yolo::Box_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _numDetected_type;
  _numDetected_type numDetected;

   typedef boost::array< ::ros_yolo::Box_<ContainerAllocator> , 6>  _bbox_type;
  _bbox_type bbox;





  typedef boost::shared_ptr< ::ros_yolo::ArmorPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_yolo::ArmorPoints_<ContainerAllocator> const> ConstPtr;

}; // struct ArmorPoints_

typedef ::ros_yolo::ArmorPoints_<std::allocator<void> > ArmorPoints;

typedef boost::shared_ptr< ::ros_yolo::ArmorPoints > ArmorPointsPtr;
typedef boost::shared_ptr< ::ros_yolo::ArmorPoints const> ArmorPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_yolo::ArmorPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_yolo::ArmorPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_yolo::ArmorPoints_<ContainerAllocator1> & lhs, const ::ros_yolo::ArmorPoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.numDetected == rhs.numDetected &&
    lhs.bbox == rhs.bbox;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_yolo::ArmorPoints_<ContainerAllocator1> & lhs, const ::ros_yolo::ArmorPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_yolo::ArmorPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_yolo::ArmorPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_yolo::ArmorPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29bf3d3a8a44f27a0f27a1f9bc39e0c2";
  }

  static const char* value(const ::ros_yolo::ArmorPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29bf3d3a8a44f27aULL;
  static const uint64_t static_value2 = 0x0f27a1f9bc39e0c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_yolo/ArmorPoints";
  }

  static const char* value(const ::ros_yolo::ArmorPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 numDetected\n"
"Box[6]  bbox\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_yolo/Box\n"
"float32 xmin # xmin\n"
"float32 ymin  # ymin\n"
"float32 xmax #xmax\n"
"float32 ymax #ymax\n"
"\n"
"float32 confidence \n"
"string obj\n"
"float32 distance\n"
;
  }

  static const char* value(const ::ros_yolo::ArmorPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.numDetected);
      stream.next(m.bbox);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmorPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_yolo::ArmorPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_yolo::ArmorPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "numDetected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numDetected);
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_yolo::Box_<ContainerAllocator> >::stream(s, indent + "    ", v.bbox[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_YOLO_MESSAGE_ARMORPOINTS_H
